### Signature Assignment

Learning Goals

By completing this assignment, you will:

* Load data from a CSV file
* Convert data into NumPy arrays
* Access and process rows individually
* Perform basic numerical operations

### Step 1: Load file
You are given a CSV file named: scores.csv

In [18]:
import numpy as np

# Load the CSV, skipping the header row and ignoring the first column (names)
data = np.genfromtxt('scores.csv', delimiter=',', skip_header=1, usecols=(1, 2, 3))

print(data)
print()

num = 1
for i in data:
    sum = np.sum(i)
    avg = sum / len(i)
    val = ""
    if avg >= 85:
        val = "Excellent!"
    elif avg >= 70 and avg < 85:
        val = "Good!"
    else:
        val = "Needs Improvement."
    print(f"Student {num}: Sum = {sum}, Average = {round(avg, 2)} {val}")
    num += 1

[[80. 85. 90.]
 [70. 75. 72.]
 [88. 92. 85.]
 [92. 89. 94.]
 [65. 68. 70.]]

Student 1: Sum = 255.0, Average = 85.0 Excellent!
Student 2: Sum = 217.0, Average = 72.33 Good!
Student 3: Sum = 265.0, Average = 88.33 Excellent!
Student 4: Sum = 275.0, Average = 91.67 Excellent!
Student 5: Sum = 203.0, Average = 67.67 Needs Improvement.


### Step 2: Pre-Process Data
* Import NumPy.
* Load the numeric data from the CSV file into a NumPy array.
* Ignore the header row.
* Ignore the first column (names).

NameError: name 'data' is not defined

### Step 3: Process Each Row

For each student (each row in the array):

* Convert the row into a NumPy array.

    Calculate:

        - Total score

        - Average score

Print the results in this format:

Student 1 - Total: __ , Average: __

### Step 4: Conditional Processing

For each student:

    * If the average is ≥ 85, print "Excellent"
    * If the average is between 70 and 84, print "Good"
    * Otherwise, print "Needs Improvement"

Reflection: To what extent and how did your work on this assignment help you learn
this learning outcome:

Answer: this project allowed us to gain hands on experience with python modules such as numpy, as well as continue to develop our understanding of loading and reading files such as csv files.